name: Carlos Gomez
title: Carlos Gomez
markdown: kramdown
highlighter: rouge # or pygments or null
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock"]

baseurl: /cg-blog
